trigger:
- main   # run pipeline on commits to main branch

pool:
  vmImage: ubuntu-latest

variables:
  node_version: '20.x'
  webAppName: 'ecommerce-webapp-demo'   # your Azure Web App name
  azureSubscription: 'AzureConnection'  # created in DevOps service connections
  packageDir: '$(System.DefaultWorkingDirectory)'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(node_version)'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build || echo "No build step"
  displayName: 'Install dependencies and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(packageDir)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appName: '$(webAppName)'
    slotName: 'staging'   # deploy to staging slot
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
